### ISSUE TITLE
Using with require.js error

### ISSUE THREAD

**Issue by RokaFogtaCsukaFarka** [sindresorhus/ip-regex#10]
Greetings!

I have used this library with the latest require.js and I got the following error:
Uncaught ReferenceError: module is not defined
    at index.js:22

My syntax is the following:
```javascript
define(["../node_modules/ip-regex/index"], function(ipTestModule) {
   const ipRegex = ipTestModule;
   function(ip) {
      return this.ipRegex.v4({exact:true}).test(ip);
   }
);
```
This fails always!

Thanks for your contribution...

**Comment by SamVerschueren** [comment]
We target Node.js, not browsers. It's up to Require.js to make sure that node modules work. Apparently they don't, I suggest looking into something like Webpack.
