### ISSUE TITLE
Uglifyjs error

### ISSUE THREAD

**Issue by gate3** [sindresorhus/ip-regex#11]
Hi, I am using this package with create react app, anytime I try to build the app. Uplifyjs throws an error on line 6 of indexjs because of the character `. Please is there a walk around for this? Thanks

**Comment by Mottie** [comment]
UglifyJS2 doesn't currently support ES2015 - see [this note](https://github.com/mishoo/UglifyJS2/#note) - use [Uglify-es](https://github.com/mishoo/UglifyJS2/tree/harmony) or [babili](https://github.com/babel/babili) instead.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
