### ISSUE TITLE
IE issue

### ISSUE THREAD

**Issue by madaraveilande** [sindresorhus/ip-regex#13]
Hi!
This place on the 6th line:
![image](https://user-images.githubusercontent.com/6758142/30364380-ab83c3b0-986c-11e7-96fc-dde6333c22b4.png)
Is making a syntax error (invalid character) on Internet Explorer. Is there something you can do about this?

**Comment by kevva** [comment]
Which version of IE? Template literals are not supported in older versions of IE other than Edge. You have to transpile the package before using it. This package is mainly intended for usage on Node.js. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by BionBit** [comment]
Not necessary to use 'babel-engine-plugin'.
In this case, you should manually include all of the 'ip-regex's dependencies in webpack for transpilation.

An example of using 'include + exclude' in a webpack rule,
https://github.com/webpack/webpack/issues/2031
