### ISSUE TITLE
Minify build problem 

### ISSUE THREAD

**Issue by somarjun** [sindresorhus/ip-regex#17]
Im trying to build my application and it raises this..
Failed to minify the code from this file: 

        ./node_modules/ip-regex/index.js:6 

Read more here: http://bit.ly/2tRViJ9

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
