### ISSUE TITLE
[Feature Request] Allow to determine whether an IP address is a "loopback" address

### ISSUE THREAD

**Issue by Gaboik** [sindresorhus/ip-regex#22]
I think it would be useful to be able to determine whether a given valid IP address is a "loopback" IP address or not.  The reason I think this could be useful is that it is often necessary to validate if an IP address is a "loopback" address for security purposes and what better place to do that than in an IP address validation package?

One way to expose this behavior would be to use the 'options' object passed to either the `.v4()` or `.v6()` methods, such as :
```javascript
const noLoopback = require('ip-regex').v4({ exact: true, matchLoopbackAddresses: false });
```

This way, a typical use case of the feature could look like this
```javascript
const ipregex = require('ip-regex''');

const allowLoopback = ipregex.v4({ exact: true });

allowLoopback.test('127.0.0.1');.   // true

const noLoopback = ipregex.v4({.exact: true, allowLoopbackAdresses: false });

noLoopback.test('127.0.0.1');.   // false

noLoopback.test('8.8.8.8');.   // true

noLoopback.test('localhost');.   // false
```

Now, as for the implementation itself, even if the module is named "ip-regex", I think using node,js' 'os' module to get the loopback network interfaces of the machine on which the node process is running would be more efficient and effective than using a regex that tries to guess every possible loopback address because after some research, it appears to me that the supported loopback address range can vary depending on the operating system.

**Comment by sindresorhus** [comment]
This is outside the scope of this module. You can implement it yourself by filtering out the results afterwards.
