### ISSUE TITLE
Cloud provide an dist file within for npm?

### ISSUE THREAD

**Issue by zrb0001** [sindresorhus/ip-regex#25]
Sometimes i need run project in IE 11, but string template is illegal, it make me have to spend extra time to configure like babel in webpack.

So, could provide a dist version(ES5) in npm package, and it is default file to be imported when require in project.

Thanks.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
