### ISSUE TITLE
Positive lookbehind when includeBoundaries is true doesn't work with Safari

### ISSUE THREAD

**Issue by oalders** [sindresorhus/ip-regex#34]
Hi. Thanks for your sharing your work!

When using `includeBoundaries`, the positive lookbehind in the regex which is assigned to `const boundry` causes an error under Safari.

```javascript
import ipRegex from './index.js';

const replace = function (raw) {
  return raw.replace(/,/g, ' ').match(ipRegex({includeBoundaries: true}));
};

const thing = replace('1111.1.1.1,2.2.2.2,3.3.3.333,4.4.4.4');
```

<img width="958" alt="Screen Shot 2022-06-24 at 17 43 24" src="https://user-images.githubusercontent.com/96205/175696856-38c6c5ed-d741-4334-9a13-50b5ed6074c3.png">

If you feel this is worth addressing, I could look into contributing a PR for it.

**Comment by sindresorhus** [comment]
I'm not interested in changing the code for Safari.
