### ISSUE TITLE
Zero-Padded IPv4s

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/ip-regex#36]
Some tools like `ipaddr.js` accept zero-padded IPv4s as valid. I think this module might consider accepting them too, even thought node's `net.isIP` also considers them invalid:

```js
> (await import("ipaddr.js")).default.parse("01.02.03.04")
IPv4 { octets: [ 1, 2, 3, 4 ] }
> (await import("ip-regex")).default({exact: true}).test("01.02.03.04")
false
> net.isIP("01.02.03.04")
0
```

Some more opinions about it [here](https://superuser.com/questions/929153).

**Comment by sindresorhus** [comment]
I don't think it's a good idea. There's ambiguity: https://superuser.com/a/858397 And there's probably a reason Node.js doesn't support it.

However, it's probably a good idea to explicitly point out in the docs that it's not supported.

**Comment by silverwind** [comment]
> There's ambiguity: https://superuser.com/a/858397

By that reasoning, zero-padded IPv6 also has ambiguity, but [it's still accepted](https://github.com/sindresorhus/ip-regex/blob/3e220cae3eb66ecfdf4f7678bea7306ceaa41c76/test.js#L130). So, to be consistent between IPv4 and IPv6 zero-padded numbers should be accepted as decimals.

**Comment by 839735495** [comment]
IMO, the textual presentation for IPv4 uses decimal base. Usually, we do not have the habit to zero-pad a value with decimal base. However, the textual presentation for IPv6 uses hex base. It is ok to zero-pad for a hex base number I think.

**Comment by silverwind** [comment]
It's certainly in use in old systems from the 80s and 90s. I know one that even requires zero-padded IPv4s. In fact the IP Address format was first specified with zero padding in [RFC790](https://datatracker.ietf.org/doc/html/rfc790):

>    One notation for internet host addresses commonly used divides the
>   32-bit address into four 8-bit fields and specifies the value of each
>   field as a decimal number with the fields separated by periods.  For
>   example, the internet address of ISIF is 010.020.000.052.

**Comment by silverwind** [comment]
Reasonable to close I guess, but also makes me wonder though why zero-padding is allowed for IPv6 but not for IPv4:

````js
> (await import("./index.js")).default.v6().test("::0001")
true
````

**Comment by silverwind** [comment]
At least it's an easy workaround:

````js
> (await import("./index.js")).default.v4().test("001.002.03.4".split(".").map(Number).join("."))
true
````
