### ISSUE TITLE
v6not

### ISSUE THREAD

**Issue by simon-p-r** [sindresorhus/ip-regex#6]
Hi

In your test data for v6not you have a value of **::** which according to this [tool](http://www.helpsystems.com/intermapper/ipv6-test-address-validation) should be valid.  I have found this [module](https://github.com/AnatoliyGatt/is-ipv6-node) which appears to validate correctly.  I will do a PR to add more test data if you want.

Thanks

**Comment by SamVerschueren** [comment]
I verified it as well and `::` seems to be equal to `0.0.0.0` on v4.

Or do a PR to fix it ;)

**Comment by simon-p-r** [comment]
No good with regexs still learning so don't know if I can fix at the moment :disappointed:

**Comment by silverwind** [comment]
Also fails to recognize `::1`. I think this module could just replicate node's `net.isIPv{4,6}`.
